project:
  type: website
  output-dir: docs

website:
  #title: "suvendusamanta.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - href: about.qmd
        text: About me
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



