project:
  type: website
  output-dir: docs

website:
  title: "Home"
  navbar:
    left:
      - href: guide.qmd
        text: Guide
      - href: blog.qmd
        text: Blog
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false



